const CACHE_NAME = "fast_io-docs-v41";
const urlsToCache = [
  "/",
  "/style.css",
  "/script.js",
  "/sw-register.js",
  "/manifest.json",
  "/icons/logo.webp",
  "/docs/00.intro/",
  "/docs/00.intro/01.fastio/",
  // "/docs/api/",
  "/docs/01.compile/",
  "/docs/01.compile/01.pwastore/",
  "/docs/01.compile/01.pwastore/01.webp",
  "/docs/01.compile/01.pwastore/02.webp",
  "/docs/01.compile/01.pwastore/03.webp",
  "/docs/01.compile/02.vscode/",
  "/docs/01.compile/02.vscode/autosavedisable.webp",
  "/docs/01.compile/03.compilers/",
  "/docs/01.compile/04.clang/",
  "/docs/01.compile/05.testinstallation/",
  "/docs/01.compile/06.gcc/",
  "/docs/01.compile/07.msvc/",
  "/docs/01.compile/08.fastio/",
  "/docs/02.basics/",
  "/docs/02.basics/01.helloworld/",
  "/docs/02.basics/02.datatypes/",
  "/docs/02.basics/02.datatypes/01.ascii/",
  "/docs/02.basics/03.literals/",
  "/docs/02.basics/04.initialization/",
  "/docs/02.basics/05.assignment/",
  "/docs/02.basics/06.operators/",
  "/docs/02.basics/07.sizeof/",
  "/docs/02.basics/08.const/",
  "/docs/02.basics/09.reference/",
  "/docs/02.basics/10.auto/",
  "/docs/02.basics/11.decltype/",
  "/docs/02.basics/12.decltypeauto/",
  "/docs/02.basics/13.casting/",
  "/docs/02.basics/14.a+b/",
  "/docs/02.basics/15.limits/",
  "/docs/02.basics/16.enumclass/",
  "/docs/02.basics/17.bit/",
  "/docs/02.basics/18.endian/",
  "/docs/02.basics/19.usingtypedef/",
  "/docs/02.basics/20.byte/",
  "/docs/02.basics/21.struct/",
  "/docs/03.statements/",
  "/docs/03.statements/01.empty/",
  "/docs/03.statements/02.compound/",
  "/docs/03.statements/03.if/",
  "/docs/03.statements/04.while/",
  "/docs/03.statements/05.for/",
  "/docs/03.statements/06.break/",
  "/docs/03.statements/07.continue/",
  "/docs/03.statements/08.dowhile/",
  "/docs/03.statements/09.switch/",
  "/docs/03.statements/10.goto/",
  "/docs/03.statements/11.preprocessor/",
  "/docs/03.statements/12.ifdefifndef/",
  "/docs/03.statements/13.attribute/",
  "/docs/03.statements/14.stringify/",
  "/docs/03.statements/15.featuretesting/",
  "/docs/04.dsal/",
  "/docs/04.dsal/01.string/",
  "/docs/04.dsal/02.char_category/",
  "/docs/04.dsal/03.vector/",
  "/docs/04.dsal/04.array/",
  "/docs/04.dsal/05.multidcontainers/",
  "/docs/05.pointerscarray/",
  "/docs/05.pointerscarray/01.address/",
  "/docs/05.pointerscarray/02.pointerbasics/",
  "/docs/05.pointerscarray/03.dereference/",
  "/docs/05.pointerscarray/04.nullptr/",
  "/docs/05.pointerscarray/05.cstylearray/",
  "/docs/05.pointerscarray/06.pointerarithmetic/",
  "/docs/05.pointerscarray/07.carraydecay/",
  "/docs/05.pointerscarray/08.cstylestring/",
  "/docs/05.pointerscarray/09.multidim/",
  "/docs/05.pointerscarray/10.constpointer/",
  "/docs/05.pointerscarray/11.voidpointer/",
  "/docs/05.pointerscarray/12.pointersandcontainers/",
  "/docs/05.pointerscarray/13.strictaliasing/",
  "/docs/05.pointerscarray/14.memfunctions/",
  "/docs/05.pointerscarray/15.pointerpitfalls/",
  "/docs/05.pointerscarray/16.pointerbestpractices/",
  "/docs/06.function/",
  "/docs/06.function/01.whatisfunction/",
  "/docs/06.function/02.declarationdefinition/",
  "/docs/06.function/03.arguments/",
  "/docs/06.function/04.return/",
  "/docs/06.function/05.defaultargs/",
  "/docs/06.function/06.overload/",
  "/docs/06.function/07.translationunits/",
  "/docs/06.function/08.inline/",
  "/docs/06.function/09.carrayparameters/",
  "/docs/06.function/10.fastioviews/",
  "/docs/06.function/11.recursion/",
  "/docs/06.function/12.functionpointers/",
  "/docs/06.function/13.lambda/",
  "/docs/06.function/14.higherorder/",
  "/docs/06.function/15.bestpractices/",
  "/docs/07.compiletimeprogramming/",
  "/docs/07.compiletimeprogramming/01.constexprfunction/",
  "/docs/07.compiletimeprogramming/02.constexprobjects/",
  "/docs/07.compiletimeprogramming/03.ifconstexpr/",
  "/docs/07.compiletimeprogramming/04.ifconsteval/",
  "/docs/07.compiletimeprogramming/05.constinit/",
  "/docs/07.compiletimeprogramming/06.consteval/",
  '/docs/08.algorithm/',
  '/docs/08.algorithm/01.ranges/',
  '/docs/08.algorithm/02.rangecategories/',
  '/docs/08.algorithm/03.iteratorcategories/',
  '/docs/08.algorithm/04.iteratoralgorithms/',
  '/docs/08.algorithm/05.projections/',
  '/docs/08.algorithm/06.typical/',
  '/docs/08.algorithm/07.numeric/',
  '/docs/08.algorithm/08.timecomplexity/',
  '/docs/08.algorithm/08.timecomplexity/01.master/',
  '/docs/08.algorithm/09.rammachine/',
  '/docs/08.algorithm/10.zerocost/',
  '/docs/09.seqcontainers/',
  '/docs/09.seqcontainers/01.overview/',
  '/docs/09.seqcontainers/02.commonops/',
  '/docs/09.seqcontainers/03.inserteraseindex/',
  '/docs/09.seqcontainers/04.iterators/',
  '/docs/09.seqcontainers/05.unchecked/',
  '/docs/09.seqcontainers/06.forwardlist/',
  '/docs/09.seqcontainers/07.listspecialops/',
  '/docs/09.seqcontainers/08.vectorcapacity/',
  '/docs/09.seqcontainers/09.deque/',
  '/docs/09.seqcontainers/10.span/',
  '/docs/09.seqcontainers/11.bitvec/',
  '/docs/09.seqcontainers/12.string/',
  '/docs/09.seqcontainers/12.string/01.ops/',
  '/docs/09.seqcontainers/13.stringview/',
  '/docs/09.seqcontainers/13.stringview/01.ops/',
  '/docs/09.seqcontainers/14.adapters/',
  '/docs/09.seqcontainers/15.algorithms/',
  '/docs/09.seqcontainers/16.std/',
  '/docs/11.io/',
  '/docs/11.io/01.fileio/',
  '/docs/11.io/02.customtypes/',
  '/docs/11.io/03.manipulators/',
  '/docs/11.io/03.manipulators/01.manipulators/',
  '/docs/11.io/04.operations/',
  '/docs/11.io/05.buffered/',
  '/docs/11.io/06.mutex/',
  '/docs/11.io/07.randomaccess/',
  '/docs/11.io/08.fileloader/',
  '/docs/11.io/09.stringrelation/',
  '/docs/11.io/10.socket/',
  '/docs/11.io/10.socket/01.networkbasics/',
  '/docs/11.io/10.socket/02.dns/',
  '/docs/11.io/10.socket/03.modernprotocols/',
  '/docs/11.io/10.socket/04.protocolsupport/',
  '/docs/11.io/11.cstyle/',
  '/docs/11.io/11.cstyle/01.creference/',
  '/docs/11.io/12.iostream/',
  '/docs/11.io/12.iostream/01.cppreference/',
  '/docs/11.io/12.iostream/02.iomanip/',
  '/docs/11.io/13.posix/',
  '/docs/11.io/14.win32/',
  '/docs/11.io/15.nt/',
  '/docs/11.io/16.wine/',
  '/docs/11.io/17.layers/',
  '/docs/11.io/18.filesystem/',
  '/docs/11.io/19.temp/',
  '/docs/12.random/',
  '/docs/12.random/01.engines/',
  '/docs/12.random/02.distributions/',
  '/docs/12.random/03.ibufwhitehole/',
  '/docs/12.random/04.seedseq/',
  '/docs/12.random/05.shuffle/',
  '/docs/12.random/06.security/',
  '/docs/12.random/07.distributions/',
  '/docs/12.random/08.examples/',
  '/docs/12.random/08.examples/01.proof/',
];

// Install: pre-cache resources
self.addEventListener("install", event => {
  event.waitUntil(
    caches.open(CACHE_NAME).then(cache => cache.addAll(urlsToCache))
  );
  self.skipWaiting(); // activate new worker immediately
});

// Activate: remove old caches
self.addEventListener("activate", event => {
  event.waitUntil(
    caches.keys().then(keys =>
      Promise.all(
        keys.filter(key => key !== CACHE_NAME)
            .map(key => caches.delete(key))
      )
    )
  );
  self.clients.claim(); // take control of all pages
});

// Fetch: cache-first with network fallback
self.addEventListener("fetch", event => {
  event.respondWith(
    caches.match(event.request).then(response => {
      return response || fetch(event.request);
    })
  );
});

// Listen for messages from the client
self.addEventListener("message", event => {
  if (event.data === "SKIP_WAITING") {
    self.skipWaiting();
  }
});
